export const initialValuesGeneralForm = {
  GENERALIDADES: {
    GEORREFERENCIACION: "",
    ID_TIPO_ACCESO: "",
    INDICACIONES_ACCESO: "",
    CORREGIMIENTO_VEREDA_LOCALIDAD: "",
    ID_DEPARTAMENTOS: "",
    ID_MUNICIPIOS: "",
    NOMBRE: "",
    UBICACION: "",
  },
  CARACTERISTICAS: {
    DESCRIPCION: "",
    IMAGEN1: null,
    IMAGEN2: null,
    FUENTE: "",
  },
  CARACTERISTICAS_RELEVANTES: {
    ID_TIPO_CLIMA: "",
    TEMPERATURA: "",
    ACCESO_HORARIOS: {
      RESTRINGIDO: false,
      PERMANENTE: false,
      VISITA_EXTERIOR: false,
      VISITA_INTERIOR: false,
    },
    DIAS_HORARIOS: {
      LUNES: false,
      MARTES: false,
      MIERCOLES: false,
      JUEVES: false,
      VIERNES: false,
      SABADO: false,
      DOMINGO: false,
    },
    ID_TIPO_ESTADO: "",
  },
  ACTIVIDADES_SERVICIOS: {
    ACTIVIDADES: {
      CULTURALES: "",
      ARTISTICAS: "",
      FISICAS: "",
      RECREATIVAS: "",
      OTROS: "",
    },
    SERVICIOS: {
      TIENDAS: "",
      GUIAS: "",
      BANOS: "",
      RESTAURANTES: "",
      PARQUEADERO: "",
      ALOJAMIENTO: "",
      OTROS: "",
    },
  },
  PROMOCION: {
    FOLLETOS_GUIAS: "",
    PUBLICACIONES: "",
    TRIPADVISOR: "",
    CTRAVEL: "",
    GOOGLEM: "",
    PAGINA_WEB: "",
    YOUTUBE: "",
    OTROS: "",
  },
  SERVICIOS_ESPECIALES: {
    ASCENSORES: "",
    RAMPAS: "",
    DISCAP_AUDITIVA: "",
    BANOS: "",
    MOVILIDAD: "",
    OTROS: "",
  },
  OTROS: {
    REDES: {
      PAGINA_WEB: "",
      FACEBOOK: "",
      TWITTER: "",
      INSTAGRAM: "",
      OTRA: "",
    },
    REF_BIBLIOGRAFICA: "",
    OBSERVACIONES: "",
  },
};